# [START gae_python37_cloudsql_config] 
runtime: python37 
 
env_variables: 
  CLOUD_SQL_USERNAME: CainBurt 
  CLOUD_SQL_PASSWORD: Password123  
  CLOUD_SQL_DATABASE_NAME: demo  
  CLOUD_SQL_CONNECTION_NAME: ad-lab02:europe-west2:lab3
# [END gae_python37_cloudsql_config] 